/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

import Model.EcoSystem;
import Model.Enterprise.Enterprise;
import Model.Network.Network;
import Model.Organization.Organization;
import Model.Role.Role;
import Model.User.UserAccount;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author tiankaining
 */
public class AdminWorkAreaPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem system;
    private Network network;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAccount;
    private Role role;

    private CardLayout cardLayout;
    private JPanel contentPanel;

    public AdminWorkAreaPanel(JPanel userProcessContainer, EcoSystem system, UserAccount userAccount) {
        this.userProcessContainer = userProcessContainer;
        this.system = system;
    // ✅ 初始化默认network/enterprise/org
    this.network = system.getNetworkDirectory().getAllNetworks().get(0);
    this.enterprise = network.getEnterpriseDirectory().getEnterpriseList().get(0);
    this.organization = enterprise.getOrganizations().getOrganizationList().get(0);
        this.userAccount = userAccount;
//        this.role = role;

        initComponents();

        initComponents(); // 初始化按钮等UI
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageUserAccounts = new javax.swing.JButton();
        btnNetworkAdminReports = new javax.swing.JButton();
        btnManageOrganization = new javax.swing.JButton();
        btnManageNetwork = new javax.swing.JButton();
        btnManageEnterprise = new javax.swing.JButton();
        btnManageRoles = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Admin Workarea");

        btnManageUserAccounts.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnManageUserAccounts.setText("Manage User Accounts");
        btnManageUserAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserAccountsActionPerformed(evt);
            }
        });

        btnNetworkAdminReports.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnNetworkAdminReports.setText("Network Admin Reports");
        btnNetworkAdminReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetworkAdminReportsActionPerformed(evt);
            }
        });

        btnManageOrganization.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnManageOrganization.setText("Manage Organization");
        btnManageOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganizationActionPerformed(evt);
            }
        });

        btnManageNetwork.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnManageNetwork.setText("Manage Network");
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });

        btnManageEnterprise.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnManageEnterprise.setText("Manage Enterprise");
        btnManageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseActionPerformed(evt);
            }
        });

        btnManageRoles.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnManageRoles.setText("Manage User Roles");
        btnManageRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRolesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnManageRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnManageUserAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNetworkAdminReports, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnManageNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnManageEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnManageOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(jLabel1)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNetworkAdminReports, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageUserAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(287, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageUserAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserAccountsActionPerformed
    ManageUserAccounts panel = new ManageUserAccounts(userProcessContainer, getDefaultOrganization());
    userProcessContainer.add("ManageUserAccountsPanel", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.show(userProcessContainer, "ManageUserAccountsPanel");
    }//GEN-LAST:event_btnManageUserAccountsActionPerformed

    private void btnNetworkAdminReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetworkAdminReportsActionPerformed
    NetworkAdminReports panel = new NetworkAdminReports();
    userProcessContainer.add("NetworkAdminReportsPanel", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.show(userProcessContainer, "NetworkAdminReportsPanel");
    }//GEN-LAST:event_btnNetworkAdminReportsActionPerformed

    private void btnManageOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganizationActionPerformed
    ManageOrganization panel = new ManageOrganization(
        userProcessContainer, 
        getDefaultOrganizationDirectory(), 
        getDefaultEnterprise()
    );
    userProcessContainer.add("ManageOrganizationPanel", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.show(userProcessContainer, "ManageOrganizationPanel");
    }//GEN-LAST:event_btnManageOrganizationActionPerformed

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed
    ManageNetwork panel = new ManageNetwork(userProcessContainer, system);
    userProcessContainer.add("ManageNetworkPanel", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.show(userProcessContainer, "ManageNetworkPanel");
    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void btnManageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseActionPerformed
    ManageEnterprise panel = new ManageEnterprise(userProcessContainer, getDefaultNetwork());
    userProcessContainer.add("ManageEnterprisePanel", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.show(userProcessContainer, "ManageEnterprisePanel");
    }//GEN-LAST:event_btnManageEnterpriseActionPerformed

    private void btnManageRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRolesActionPerformed
    ManageRoles panel = new ManageRoles(
        userProcessContainer, 
        getDefaultEnterprise(), 
        getDefaultOrganization(), 
        getDefaultOrganization().getRoleDirectory()
    );
    userProcessContainer.add("ManageRolesPanel", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.show(userProcessContainer, "ManageRolesPanel");
    }//GEN-LAST:event_btnManageRolesActionPerformed
    // 辅助方法
public Network getDefaultNetwork() {
    return network;
}

public Enterprise getDefaultEnterprise() {
    return enterprise;
}

public Organization getDefaultOrganization() {
    return organization;
}


    private Model.Organization.OrganizationDirectory getDefaultOrganizationDirectory() {
        Model.Enterprise.Enterprise enterprise = getDefaultEnterprise();
        if (enterprise != null) {
            return enterprise.getOrganizations();
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageEnterprise;
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JButton btnManageOrganization;
    private javax.swing.JButton btnManageRoles;
    private javax.swing.JButton btnManageUserAccounts;
    private javax.swing.JButton btnNetworkAdminReports;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
