/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.EmergencyDispatcher;

import Model.EcoSystem;
import Model.Organization.Organization;
import Model.User.UserAccount;
import javax.swing.JPanel;
import java.awt.CardLayout;

/**
 *
 * @author tiankaining
 */
public class EmergencyDispatcherWorkAreaPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Organization organization;
    private UserAccount userAccount;
    private EcoSystem system;
    
    private CardLayout cardLayout;
    private JPanel contentPanel;

    public EmergencyDispatcherWorkAreaPanel(JPanel userProcessContainer, Organization organization, UserAccount userAccount) {
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.userAccount = userAccount;
        this.system = EcoSystem.getInstance(); // Assuming EcoSystem is a singleton

        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRequestManagement = new javax.swing.JButton();
        btnResponderStats = new javax.swing.JButton();
        btnTaskTracking = new javax.swing.JButton();
        btnRequestCreate = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Emergency Dispatcher WorkArea");

        btnRequestManagement.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnRequestManagement.setText("Request Management");
        btnRequestManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestManagementActionPerformed(evt);
            }
        });

        btnResponderStats.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnResponderStats.setText("Responder Status");
        btnResponderStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponderStatsActionPerformed(evt);
            }
        });

        btnTaskTracking.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnTaskTracking.setText("Task Tracking");
        btnTaskTracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaskTrackingActionPerformed(evt);
            }
        });

        btnRequestCreate.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnRequestCreate.setText("Request Create");
        btnRequestCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(325, 325, 325))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRequestManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRequestCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnResponderStats, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTaskTracking, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(183, 183, 183))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequestCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResponderStats, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequestManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaskTracking, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestCreateActionPerformed
        // Navigate to RequestCreate
        userProcessContainer.add("RequestCreate", contentPanel.getComponent(0));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnRequestCreateActionPerformed

    private void btnResponderStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponderStatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResponderStatsActionPerformed

    private void btnRequestManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestManagementActionPerformed
        // Navigate to RequestManagement
        userProcessContainer.add("RequestManagement", contentPanel.getComponent(1));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnRequestManagementActionPerformed

    private void btnTaskTrackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaskTrackingActionPerformed
        // Navigate to RequestTracking
        userProcessContainer.add("RequestTracking", contentPanel.getComponent(2));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnTaskTrackingActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequestCreate;
    private javax.swing.JButton btnRequestManagement;
    private javax.swing.JButton btnResponderStats;
    private javax.swing.JButton btnTaskTracking;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
