/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PayrollOfficer;

import Model.Organization.Organization;
import Model.Organization.OperationsSupportUnit;
import Model.User.UserAccount;
import Model.Employee.PayrollRecord;
import Model.Enterprise.Enterprise;
import Model.Organization.OrganizationDirectory;
import Model.WorkQueue.PayrollRequest;
import Model.WorkQueue.Report;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import java.awt.CardLayout;
import java.util.Date;
import java.util.Calendar;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.ArrayList;
import java.text.SimpleDateFormat;

/**
 *
 * @author tiankaining
 */
public class PayrollOfficerWorkAreaPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private OrganizationDirectory organizationDirectory;
    private UserAccount userAccount;
    private OperationsSupportUnit operationsUnit;
    private Enterprise enterprise;


    private CardLayout cardLayout;
    private JPanel contentPanel;
    
    public PayrollOfficerWorkAreaPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount authenticatedUser) {
    this.userProcessContainer = userProcessContainer;
    this.enterprise = enterprise;
    this.userAccount = authenticatedUser;

    initComponents(); // 初始化 UI（如果你用了 GUI builder）
    
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnGeneratePayrolls = new javax.swing.JButton();
        btnTotalPayrollChart = new javax.swing.JButton();
        btnCaculateMonthCost = new javax.swing.JButton();
        btnManageEmployeeSalary = new javax.swing.JButton();
        cmbTimeSpan = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Payroll Officer WorkArea");

        btnGeneratePayrolls.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnGeneratePayrolls.setText("Generate Payrolls");
        btnGeneratePayrolls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratePayrollsActionPerformed(evt);
            }
        });

        btnTotalPayrollChart.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnTotalPayrollChart.setText("Total Payroll Chart");
        btnTotalPayrollChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalPayrollChartActionPerformed(evt);
            }
        });

        btnCaculateMonthCost.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnCaculateMonthCost.setText("Caculate Month Cost");
        btnCaculateMonthCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaculateMonthCostActionPerformed(evt);
            }
        });

        btnManageEmployeeSalary.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnManageEmployeeSalary.setText("Manage Employee Salary");
        btnManageEmployeeSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployeeSalaryActionPerformed(evt);
            }
        });

        cmbTimeSpan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "3 days", "7 days", "30 days" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnManageEmployeeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(btnTotalPayrollChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGeneratePayrolls, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCaculateMonthCost, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(cmbTimeSpan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(jLabel1)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGeneratePayrolls, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbTimeSpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCaculateMonthCost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotalPayrollChart, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageEmployeeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(226, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeneratePayrollsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePayrollsActionPerformed
        // Navigate to GeneratePayrolls
        userProcessContainer.add("GeneratePayrolls", contentPanel.getComponent(0));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnGeneratePayrollsActionPerformed

    private void btnTotalPayrollChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalPayrollChartActionPerformed

    }//GEN-LAST:event_btnTotalPayrollChartActionPerformed

    private void btnCaculateMonthCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaculateMonthCostActionPerformed

    }//GEN-LAST:event_btnCaculateMonthCostActionPerformed

    private void btnManageEmployeeSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployeeSalaryActionPerformed
        // Navigate to ManageEmployeeSalary
        userProcessContainer.add("ManageEmployeeSalary", contentPanel.getComponent(0));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnManageEmployeeSalaryActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaculateMonthCost;
    private javax.swing.JButton btnGeneratePayrolls;
    private javax.swing.JButton btnManageEmployeeSalary;
    private javax.swing.JButton btnTotalPayrollChart;
    private javax.swing.JComboBox<String> cmbTimeSpan;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
