/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SupplychainManager;

import Model.Organization.Organization;
import Model.Organization.SupplyChainManagementUnit;
import Model.User.UserAccount;
import Model.Supplies.SupplyItemCatalog;
import Model.Supplies.DeliveryCatalog;
import javax.swing.JPanel;
import java.awt.CardLayout;

/**
 *
 * @author tiankaining
 */
public class SupplyOfficerWorkAreaPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Organization organization;
    private UserAccount userAccount;

    private CardLayout cardLayout;
    private JPanel contentPanel;

    public SupplyOfficerWorkAreaPanel(JPanel userProcessContainer, Organization organization, UserAccount userAccount) {
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.userAccount = userAccount;

        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSupplyUsageTracking = new javax.swing.JButton();
        btnManageStock = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnManageSupplyRequests = new javax.swing.JButton();
        btnManageShipment = new javax.swing.JButton();

        btnSupplyUsageTracking.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnSupplyUsageTracking.setText("Supply Usage Tracking");
        btnSupplyUsageTracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplyUsageTrackingActionPerformed(evt);
            }
        });

        btnManageStock.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnManageStock.setText("Manage Stock");
        btnManageStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStockActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Supply Chain Manage");

        btnManageSupplyRequests.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnManageSupplyRequests.setText("Manage Supply Requests");
        btnManageSupplyRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSupplyRequestsActionPerformed(evt);
            }
        });

        btnManageShipment.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnManageShipment.setText("Manage Shipment");
        btnManageShipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageShipmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnManageSupplyRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(btnSupplyUsageTracking, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnManageStock, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(btnManageShipment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(194, 194, 194))
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageStock, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageShipment, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupplyUsageTracking, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageSupplyRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSupplyUsageTrackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplyUsageTrackingActionPerformed
        // Navigate to SupplyUsageTracking (labeled as Track Applications)
        userProcessContainer.add("SupplyUsageTracking", contentPanel.getComponent(1));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnSupplyUsageTrackingActionPerformed

    private void btnManageStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStockActionPerformed
        // Navigate to ManageStock (labeled as Manage Inventory)
        userProcessContainer.add("ManageStock", contentPanel.getComponent(0));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnManageStockActionPerformed

    private void btnManageSupplyRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSupplyRequestsActionPerformed
        // Navigate to ManageSupplyRequests (labeled as Manage Supplies Applications)
        userProcessContainer.add("ManageSupplyRequests", contentPanel.getComponent(2));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnManageSupplyRequestsActionPerformed

    private void btnManageShipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageShipmentActionPerformed
        // Navigate to SupplyUsageTracking (labeled as Track Applications)
        userProcessContainer.add("ManageShipment", contentPanel.getComponent(1));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnManageShipmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageShipment;
    private javax.swing.JButton btnManageStock;
    private javax.swing.JButton btnManageSupplyRequests;
    private javax.swing.JButton btnSupplyUsageTracking;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
