/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HospitalNurse;

import Model.Organization.ClinicalServicesUnit;
import Model.Organization.Organization;
import Model.User.UserAccount;
import Model.Patient.PatientDirectory;
import Model.Supplies.ICUbedCatalog;
import javax.swing.JPanel;
import java.awt.CardLayout;

/**
 *
 * @author tiankaining
 */
public class HospitalNurseWorkArea extends javax.swing.JPanel {

private JPanel userProcessContainer;
private Organization organization;
private UserAccount userAccount;
private CardLayout cardLayout;
private JPanel contentPanel;

public HospitalNurseWorkArea(JPanel userProcessContainer, Organization organization, UserAccount userAccount) {
    this.userProcessContainer = userProcessContainer;
    this.organization = organization;
    this.userAccount = userAccount;

    initComponents();
    
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManagePatientCarePlans = new javax.swing.JButton();
        btnManageICUPatientMonitoring = new javax.swing.JButton();
        btnManageMedicationAdministration = new javax.swing.JButton();
        btnViewPatientShiftNotes = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Hospital Nurse WorkArea");

        btnManagePatientCarePlans.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnManagePatientCarePlans.setText("Manage Patient Care Plans");
        btnManagePatientCarePlans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePatientCarePlansActionPerformed(evt);
            }
        });

        btnManageICUPatientMonitoring.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnManageICUPatientMonitoring.setText("Manage ICU Patient Monitoring");
        btnManageICUPatientMonitoring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageICUPatientMonitoringActionPerformed(evt);
            }
        });

        btnManageMedicationAdministration.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnManageMedicationAdministration.setText("Manage Medication Administration");
        btnManageMedicationAdministration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMedicationAdministrationActionPerformed(evt);
            }
        });

        btnViewPatientShiftNotes.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnViewPatientShiftNotes.setText("View Patient Shift Notes");
        btnViewPatientShiftNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientShiftNotesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnViewPatientShiftNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(btnManageICUPatientMonitoring, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnManagePatientCarePlans, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(btnManageMedicationAdministration))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(jLabel1)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManagePatientCarePlans, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageMedicationAdministration, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageICUPatientMonitoring, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewPatientShiftNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagePatientCarePlansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePatientCarePlansActionPerformed
        // Navigate to ManagePatientCarePlans
        userProcessContainer.add("ManagePatientCarePlans", contentPanel.getComponent(0));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnManagePatientCarePlansActionPerformed

    private void btnManageICUPatientMonitoringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageICUPatientMonitoringActionPerformed
        // Navigate to ManageICUPatientMonitoring
        userProcessContainer.add("ManageICUPatientMonitoring", contentPanel.getComponent(2));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnManageICUPatientMonitoringActionPerformed

    private void btnManageMedicationAdministrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMedicationAdministrationActionPerformed
        // Navigate to ManageMedicationAdministration
        userProcessContainer.add("ManageMedicationAdministration", contentPanel.getComponent(1));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnManageMedicationAdministrationActionPerformed

    private void btnViewPatientShiftNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientShiftNotesActionPerformed
        // Navigate to ViewPatientShiftNotes
        userProcessContainer.add("ViewPatientShiftNotes", contentPanel.getComponent(3));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnViewPatientShiftNotesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageICUPatientMonitoring;
    private javax.swing.JButton btnManageMedicationAdministration;
    private javax.swing.JButton btnManagePatientCarePlans;
    private javax.swing.JButton btnViewPatientShiftNotes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
